### ISSUE TITLE
It overides the text file

### ISSUE THREAD

**Issue by FREAZLeY** [tharindurasmal/auto-run-wifi-password-cracker#1]
So I love this so much but one problem is when I plug it into a computer and take it out to check what I got on the other computer it overrides and deletes the wifi info I got from the other one and erases it and pastes the other one can you make it where it can eather create another file per computer or just add onto the text file. Thank you

**Comment by tharindurasmal** [comment]
Thanks for the feedback! I’m glad you’re finding the script useful. I’ve updated it to prevent overwriting Wi-Fi information from multiple computers. Depending on what you need, it creates a unique file for each computer.

**Comment by tharindurasmal** [comment]
Thanks for the feedback! I’m glad you’re finding the script useful. I’ve
updated it to prevent overwriting Wi-Fi information from multiple
computers. Depending on what you need, it creates a unique file for each
computer.
